### ISSUE TITLE
Device Model:Xiaomi Mi Mix 2 无法读取CPU GPU和分辨率（ps：我自己修改了MIUI国际版里提供的显示大小）

### ISSUE THREAD

**Issue by 67373upupup** [Septillion/KFMARK#18] opened 2018-11-10 00:47 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 67373upupup** [comment] 2018-11-10 00:50
手癌晚期就用截图代替了
![screenshot_2018-11-10-08-49-26-517_com af benchaf](https://user-images.githubusercontent.com/44890548/48295303-aa339e80-e4c5-11e8-98e3-cee74fd86d5d.png)
![screenshot_2018-11-10-08-49-10-115_com android se](https://user-images.githubusercontent.com/44890548/48295305-b3247000-e4c5-11e8-92a1-894c00dda89b.png)

**Comment by 67373upupup** [comment] 2018-11-10 00:52
![screenshot_2018-11-10-08-52-31-370_com android se](https://user-images.githubusercontent.com/44890548/48295344-fda5ec80-e4c5-11e8-9df7-fb3e1813a18e.png)

**Comment by 67373upupup** [comment] 2018-11-10 00:54
不对，好像是懒癌0..0.jpg

**Comment by Septillion** [comment] 2018-11-10 03:04
Duplicate of #10

**Closed by Septillion** 2018-11-10 03:04 UTC
