### ISSUE TITLE
期待新版本修复拔线未激活功能，重启之后也是激活的

### ISSUE THREAD

**Issue by code-travelle** [Septillion/KFMARK#38] opened 2018-11-13 06:18 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Septillion** [comment] 2018-11-14 06:16
Duplicate of #9

**Closed by Septillion** 2018-11-14 06:16 UTC
